_target_: evo.ParetoFrontSelector
survival_rate: 0.1
use_crowding_distance: True
metrics:
- "auroc"
- "complexity"
#- "aupr-id"
#- "aupr-ood"
#- "fpr95"
directions:
- "max"
- "min"
#- "max"
#- "max"
#- "min"