defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log

device: "cuda"
backbone: "wrn50"

n_seeds: 5

paths:
  root: "/run/media/ki/data/datasets/"
  models: "/run/media/ki/data/mln-ood/gtsrb/models/${backbone}/"
  predictions: "/run/media/ki/data/mln-ood/gtsrb/predictions/${backbone}/"

dataset: "Textures"
validate_on: "test"

min_delta: 0.01

attributes:
  - class
  - color
  - shape

mln:
  train_on: "val"
  epochs: 300
  batch_size: 40000
  lr: 0.05
  weight_decay: 0.0
  momentum: 0.0
  nesterov: False
